/* CONFIG_START: keep the object below valid JSON so contact-handler.php can read it. */
window.SITE_CONFIG = Object.freeze(
{
  "siteUrl": "https://orbit-seo.com",
  "siteLanguage": "en",
  "socialImage": "https://orbit-seo.com/assets/images/orbit-social-preview-v1.png",
  "faviconHref": "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23050504'/%3E%3Ctext x='7' y='29' fill='%23f0ede4' font-family='Arial' font-weight='900' font-size='25'%3EOR%3C/text%3E%3Ctext x='7' y='53' fill='%23f0ede4' font-family='Arial' font-weight='900' font-size='25'%3EBIT%3C/text%3E%3Crect x='49' y='55' width='9' height='3' fill='%23d8ff00'/%3E%3C/svg%3E",
  "seoPages": {
    "index.html": {"path": "", "title": "BE FOUND — ORBIT SEO Consulting", "description": "Independent SEO consulting for businesses that need practical technical fixes, a stronger content plan and steady organic growth.", "type": "ProfessionalService"},
    "audit-technical-seo.html": {"path": "audit-technical-seo.html", "title": "Audit & Technical SEO — ORBIT SEO Consulting", "description": "A technical SEO audit that finds crawl, indexation and site-structure problems, ranks them by impact and gives developers a practical fix list.", "type": "Service", "serviceType": "SEO Audit and Technical SEO"},
    "content-strategy.html": {"path": "content-strategy.html", "title": "Content Strategy — ORBIT SEO Consulting", "description": "SEO content strategy that turns customer questions and search demand into useful pages, writer-ready briefs and a focused publishing plan.", "type": "Service", "serviceType": "SEO Content Strategy"},
    "authority-growth.html": {"path": "authority-growth.html", "title": "Authority & Growth — ORBIT SEO Consulting", "description": "Practical authority building through expert content, relevant publisher relationships, credible mentions and careful performance reviews.", "type": "Service", "serviceType": "SEO Authority and Growth Consulting"},
    "contact.html": {"path": "contact.html", "title": "Contact — ORBIT SEO Consulting", "description": "Tell ORBIT SEO Consulting about your website, SEO problem, advertising enquiry or collaboration idea.", "type": "ContactPage"},
    "privacy-policy.html": {"path": "privacy-policy.html", "title": "Privacy Policy — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Privacy Policy explaining how personal data is collected, used, shared, retained and protected.", "type": "WebPage"},
    "cookies-policy.html": {"path": "cookies-policy.html", "title": "Cookies Policy — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Cookies Policy explaining consent choices, the current storage inventory and available browser controls.", "type": "WebPage"},
    "terms-of-service.html": {"path": "terms-of-service.html", "title": "Terms of Service — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Terms of Service governing use of the website, enquiries, website content and the relationship to separate consulting agreements.", "type": "WebPage"},
    "404.html": {"path": "404.html", "title": "Page Not Found — ORBIT SEO Consulting", "description": "The requested page could not be found. Return to ORBIT SEO Consulting or explore our SEO services.", "type": "WebPage", "noindex": true}
  },
  "brandName": "ORBIT",
  "brandDescriptor": "SEO CONSULTING",
  "heroEyebrow": "SEARCH AS A LIVING SYSTEM",
  "heroCopy": "We help search engines find,\nunderstand and trust\nyour business.",
  "heroStatement": "DISCOVERED / UNDERSTOOD / TRUSTED",
  "sceneTwoKicker": "DISCOVERY IS ONLY THE FIRST SIGNAL",
  "sceneTwoWordOne": "WHAT IS FOUND",
  "sceneTwoWordTwo": "MUST BE UNDERSTOOD.",
  "sceneTwoCopy": "Being found is only the start. Search engines still need to understand what each page is about and why it deserves attention.",
  "sceneThreeTitle": "ORBIT",
  "sceneThreeCopy": "Visibility attracts attention. Authority creates orbit.",
  "workKicker": "SEO IS PRACTICAL WORK",
  "workTitleOne": "VISIBILITY",
  "workTitleTwo": "IS BUILT.",
  "workIntroCopy": "Audits, technical fixes, content and authority work best when they support the same plan.",
  "workAuditTitle": "AUDIT",
  "workAuditCopy": "Find what is holding the site back.",
  "workTechnicalTitle": "TECHNICAL",
  "workTechnicalCopy": "Make important pages easier to crawl.",
  "workContentTitle": "CONTENT",
  "workContentCopy": "Answer the questions people actually ask.",
  "workAuthorityTitle": "AUTHORITY",
  "workAuthorityCopy": "Give others a reason to cite you.",
  "workVerdictOne": "RANKINGS ARE NOT PROMISED.",
  "workVerdictTwo": "THE CONDITIONS FOR THEM ARE BUILT.",
  "servicesEyebrow": "THE PRACTICE",
  "servicesTitle": "WHAT WE ACTUALLY DO.",
  "servicesIntro": "We find what is getting in the way, fix the highest-impact issues and give your team a practical plan for the months ahead.",
  "auditEyebrow": "AUDIT & TECHNICAL SEO",
  "auditSectionTitle": "Find what is blocking visibility.",
  "auditSectionCopy": "We crawl the site, review how important pages are indexed and trace problems back to their source. You get a short, ranked list of fixes instead of a hundred-page export.",
  "auditItemOneTitle": "SEO audit and priority map",
  "auditItemOneCopy": "We review crawl access, index coverage, templates and site structure. Each finding is ranked by likely impact, urgency and the effort needed to fix it.",
  "auditItemTwoTitle": "Titles, headings and page structure",
  "auditItemTwoCopy": "We rewrite or restructure the elements that help a page explain itself: titles, headings, introductions and supporting sections. The language still sounds like your brand, not an SEO template.",
  "auditItemThreeTitle": "Internal linking and crawl paths",
  "auditItemThreeCopy": "We find orphaned pages and weak navigation paths, then show where internal links can help visitors and search engines reach the pages that matter most.",
  "auditItemFourTitle": "Indexation and technical foundations",
  "auditItemFourCopy": "We check canonicals, robots rules, sitemaps, redirects, duplicate URLs and response codes, then write implementation notes your developers can use without translating an SEO report first.",
  "contentEyebrow": "CONTENT STRATEGY",
  "contentSectionTitle": "Turn search demand into useful pages.",
  "contentSectionCopy": "We start with the questions customers ask, match them to business priorities and decide which pages deserve to be created, improved or removed.",
  "contentItemOneTitle": "Keyword and search-intent mapping",
  "contentItemOneCopy": "We group searches by the problem behind them and the decision someone is trying to make. That shows which page should answer each need and where the site currently has gaps or overlap.",
  "contentItemTwoTitle": "Content architecture",
  "contentItemTwoCopy": "We organize service pages, guides and supporting resources so related subjects sit together and every important page has a clear place in the site.",
  "contentItemThreeTitle": "Editorial briefs and page planning",
  "contentItemThreeCopy": "Each brief explains who the page is for, the questions it must answer, the evidence it needs and where it should lead next. Writers get a useful brief, not a script.",
  "contentItemFourTitle": "On-page optimization",
  "contentItemFourCopy": "We improve existing copy, metadata, headings, images and internal links. The aim is a better page for the reader, not a higher keyword count.",
  "authorityEyebrow": "AUTHORITY & GROWTH",
  "authoritySectionTitle": "Build reasons to be trusted.",
  "authoritySectionCopy": "Good links usually follow good work. We help you identify what is worth citing, who would genuinely care about it and how to earn recognition without buying volume.",
  "authorityItemOneTitle": "Link-earning plan",
  "authorityItemOneCopy": "We identify research, tools, expert commentary and partnerships that could earn relevant mentions. We care more about where a link appears and why than the size of a link package.",
  "authorityItemTwoTitle": "Topical authority planning",
  "authorityItemTwoCopy": "We build supporting content around the subjects your business genuinely knows. The result is a connected body of expertise, not a collection of articles written around isolated keywords.",
  "authorityItemThreeTitle": "Performance reviews",
  "authorityItemThreeCopy": "Reviews compare the work completed with changes in indexation, relevant rankings, traffic and enquiries. We separate a useful trend from the normal week-to-week noise.",
  "authorityItemFourTitle": "Next actions your team can own",
  "authorityItemFourCopy": "Every review ends with a short list of next actions and a named owner. Your team knows what to do next and why it is worth doing.",
  "serviceDetailLinkLabel": "EXPLORE THE FULL SERVICE",
  "auditPageHref": "audit-technical-seo.html",
  "contentPageHref": "content-strategy.html",
  "authorityPageHref": "authority-growth.html",
  "servicePageBackLabel": "BACK TO SERVICES",
  "servicePageBackHref": "index.html#services",
  "companyName": "ORBIT SEO CONSULTING",
  "companyAddress": "WARSAW, POLAND",
  "corporateEmail": "HELLO@ORBIT-SEO.COM",
  "corporateEmailHref": "mailto:hello@orbit-seo.com",
  "senderEmail": "no-reply@orbit-seo.com",
  "footerLegal": "© 2026 ORBIT SEO CONSULTING",
  "footerEyebrow": "ORBIT / SEO CONSULTING",
  "footerTitleOne": "BE FOUND.",
  "footerTitleTwo": "STAY UNDERSTOOD.",
  "footerCtaLabel": "START A CONVERSATION",
  "footerCtaHref": "contact.html",
  "footerExploreLabel": "EXPLORE",
  "footerServicesLabel": "SERVICES",
  "footerContactLabel": "CONTACT",
  "footerAuditLabel": "AUDIT & TECHNICAL SEO",
  "footerContentLabel": "CONTENT STRATEGY",
  "footerAuthorityLabel": "AUTHORITY & GROWTH",
  "footerPrinciple": "NO GUARANTEED RANKINGS / ONLY ACCOUNTABLE WORK",
  "footerBackToTop": "BACK TO THE TOP",
  "privacyPolicyLabel": "PRIVACY POLICY",
  "privacyPolicyHref": "privacy-policy.html",
  "cookiesPolicyLabel": "COOKIES POLICY",
  "cookiesPolicyHref": "cookies-policy.html",
  "termsOfServiceLabel": "TERMS OF SERVICE",
  "termsOfServiceHref": "terms-of-service.html",
  "legalEffectiveLabel": "EFFECTIVE DATE",
  "legalEffectiveDate": "3 AUGUST 2026",
  "legalBackLabel": "BACK HOME",
  "legalBackHref": "index.html#site-footer",
  "serviceCtaEyebrow": "UNSURE WHERE TO BEGIN?",
  "serviceCtaTitleOne": "BRING US",
  "serviceCtaTitleTwo": "THE PROBLEM.",
  "serviceCtaCopy": "You do not need an SEO diagnosis. Tell us what is changing, underperforming or unclear.",
  "serviceCtaLabel": "FIND THE RIGHT START",
  "serviceCtaHref": "contact.html",
  "evidenceEyebrow": "THE EVIDENCE STANDARD",
  "evidenceTitle": "PROOF BEFORE PROMISES.",
  "evidenceIntro": "We will not dress up ordinary ranking movement as a breakthrough. Reports show what was changed, what happened afterwards and what the business should do next.",
  "evidenceImage": "assets/images/evidence-audit-workflow-warm-v1.webp",
  "evidenceImageAlt": "SEO audit materials arranged beside a website on a laptop",
  "evidenceImageLabel": "THE WORK / MADE VISIBLE",
  "evidenceImageCaption": "A useful audit tells the team what to fix first, who should own it and how to check the result.",
  "evidenceArtifactLabel": "DELIVERABLE",
  "evidenceSignalLabel": "WHY IT MATTERS",
  "evidenceOneIndex": "DELIVERABLE / PRIORITY MAP",
  "evidenceOneTiming": "READY FOR THE TEAM",
  "evidenceOneTitle": "A list your team can actually use.",
  "evidenceOneCopy": "Each finding names the affected pages or templates, explains the likely consequence and estimates the effort involved. The most important work is easy to spot.",
  "evidenceOneArtifact": "Issue map / implementation notes",
  "evidenceOneSignal": "What search engines can crawl and index",
  "evidenceTwoIndex": "DELIVERABLE / DECISION RECORD",
  "evidenceTwoTiming": "THE REASON STAYS ATTACHED",
  "evidenceTwoTitle": "Nobody has to guess why a change was requested.",
  "evidenceTwoCopy": "Recommendations include the customer need, the business case and the page involved. When the work reaches a writer or developer, the original reasoning goes with it.",
  "evidenceTwoArtifact": "Decision log / page rationale",
  "evidenceTwoSignal": "Who decides, who implements and why",
  "evidenceThreeIndex": "DELIVERABLE / MONTHLY REVIEW",
  "evidenceThreeTiming": "PLAIN ENGLISH",
  "evidenceThreeTitle": "Reports explain what changed and what did not.",
  "evidenceThreeCopy": "We separate completed work from changes in search performance and business results. If something has not moved yet, the report says so and explains what we are watching.",
  "evidenceThreeArtifact": "Change record / review narrative",
  "evidenceThreeSignal": "Relevant search visits and enquiries",
  "evidenceNote": "CLIENT-SPECIFIC CASE STUDIES ARE PUBLISHED ONLY WITH PERMISSION. NO FICTIONAL METRICS.",
  "evidenceCta": "ASK FOR RELEVANT EXPERIENCE",
  "fitEyebrow": "WORKING FIT",
  "fitTitle": "A GOOD FIT MATTERS.",
  "fitIntro": "SEO consulting works best when the business knows its subject, has a website worth improving and can put recommendations into practice.",
  "fitPositiveLabel": "A STRONG FIT",
  "fitPositiveOneTitle": "Established service and B2B businesses",
  "fitPositiveOneCopy": "You have a credible offer and real expertise, but the website is not bringing enough of the right people to it.",
  "fitPositiveTwoTitle": "Teams ready to implement",
  "fitPositiveTwoCopy": "A developer, writer or decision-maker is available to put the agreed work into practice.",
  "fitPositiveThreeTitle": "Experts with something useful to say",
  "fitPositiveThreeCopy": "Your team can contribute first-hand experience, examples and a point of view worth publishing.",
  "fitNegativeLabel": "NOT THE RIGHT FIT",
  "fitNegativeOneTitle": "Guaranteed rankings",
  "fitNegativeOneCopy": "No responsible consultant controls Google or promises page one in 30 days.",
  "fitNegativeTwoTitle": "Bulk content for its own sake",
  "fitNegativeTwoCopy": "We do not recommend publishing articles simply to hit a monthly quota.",
  "fitNegativeThreeTitle": "Paid-link shortcuts",
  "fitNegativeThreeCopy": "We do not buy bulk links or use tactics that put the domain at unnecessary risk.",
  "engagementEyebrow": "WAYS TO WORK TOGETHER",
  "engagementTitle": "THREE WAYS TO START.",
  "engagementIntro": "You will know what we are doing, what you will receive and what it will cost before the work begins. The right format depends on the site and the support your team already has.",
  "collaborationImage": "assets/images/client-collaboration-warm-v1.webp",
  "collaborationImageAlt": "SEO consultant and client team reviewing website pages together",
  "collaborationImageLabel": "SHARED CONTEXT / CLEAR OWNERSHIP",
  "collaborationImageCaption": "We plan the work with the people who will approve, write or build it, so recommendations do not stall after delivery.",
  "engagementOneMeta": "DIAGNOSTIC / 2–4 WEEKS",
  "engagementOneTitle": "SEO Diagnostic Sprint",
  "engagementOneCopy": "A focused audit, the five issues most worth fixing and a practical plan for the following 90 days.",
  "engagementOnePrice": "FIXED SCOPE / CUSTOM QUOTE",
  "engagementTwoMeta": "PROGRAM / 90 DAYS",
  "engagementTwoTitle": "90-Day SEO Program",
  "engagementTwoCopy": "A three-month programme combining technical fixes, content planning and authority work around an agreed set of priorities.",
  "engagementTwoPrice": "PROJECT SCOPE / CUSTOM QUOTE",
  "engagementThreeMeta": "ADVISORY / MONTHLY",
  "engagementThreeTitle": "Ongoing SEO Advisory",
  "engagementThreeCopy": "Ongoing support for internal teams that need help choosing priorities, reviewing implementation and making difficult SEO decisions.",
  "engagementThreePrice": "MONTHLY SCOPE / CUSTOM QUOTE",
  "engagementCta": "DISCUSS THE RIGHT SCOPE",
  "methodEyebrow": "A CLEAR START",
  "methodTitle": "THE FIRST 90 DAYS.",
  "methodIntro": "The first 90 days are deliberately simple: understand the site, fix the biggest problems and agree on the next piece of work.",
  "methodImage": "assets/images/seo-90-day-plan-warm-v1.webp",
  "methodImageAlt": "A practical SEO audit, five priority cards and a 90-day roadmap on a worktable",
  "methodImageLabel": "AUDIT / PRIORITIZE / BUILD",
  "methodImageCaption": "The audit, the first five priorities and the 90-day plan stay in one place, with an owner beside every action.",
  "methodAuditTitle": "Audit the system.",
  "methodAuditCopy": "Crawl the site, review the data and find the issues that are costing it visibility.",
  "methodFixTitle": "Fix what matters first.",
  "methodFixCopy": "Start with the five problems most likely to improve visibility or remove risk.",
  "methodPlanTitle": "Build the next layer.",
  "methodPlanCopy": "Begin the agreed content or authority work and decide how progress will be reviewed.",
  "expectationKicker": "AN HONEST EXPECTATION",
  "expectationTitle": "SEO moves in months, not moments.",
  "expectationCopy": "A reliable trend usually takes three to six months to appear while search engines crawl, reassess and compare. Anyone guaranteeing page one in 30 days is overselling.",
  "insightsEyebrow": "FIELD NOTES",
  "insightsTitle": "START WITH THE BASICS.",
  "insightsIntro": "Three notes for teams deciding what to fix, what to publish and which SEO advice is worth ignoring.",
  "insightOneMeta": "TECHNICAL / 06 MIN",
  "insightOneTitle": "What an SEO audit should help you decide",
  "insightOneCopyOne": "Most crawl tools can produce thousands of warnings. That does not mean thousands of things need fixing. A good audit helps the team decide what deserves attention now and what can safely wait.",
  "insightOneCopyTwo": "For each priority, ask four questions: which pages are affected, what is the likely consequence, how difficult is the fix and who can do it? The first five actions should be obvious.",
  "insightTwoMeta": "CONTENT / 07 MIN",
  "insightTwoTitle": "Why more content is often the wrong first move",
  "insightTwoCopyOne": "Publishing every week does not help if the site keeps answering the same question in slightly different ways. Sometimes the better move is to improve, merge or remove an existing page.",
  "insightTwoCopyTwo": "Before commissioning an article, decide who needs it, which question it will answer and what your business can add that is not already on the first page of results.",
  "insightThreeMeta": "AUTHORITY / 05 MIN",
  "insightThreeTitle": "A credible link has context before it has a metric",
  "insightThreeCopyOne": "A link is valuable when it appears on a relevant page, in front of the right audience and for a credible reason. A high metric on its own tells you very little.",
  "insightThreeCopyTwo": "Start by creating something worth referring to: useful research, a practical tool, a strong example or genuine expert commentary. Outreach is much easier when there is a real reason to reply.",
  "insightServiceLink": "EXPLORE THE RELATED SERVICE",
  "faqEyebrow": "BEFORE WE BEGIN",
  "faqTitle": "FAQ.",
  "faqIntro": "These are the questions clients usually ask before deciding whether SEO consulting is the right next step.",
  "faqFootnote": "ASK BETTER / BUILD BETTER",
  "faqOneQuestion": "How long does SEO take to show results?",
  "faqOneAnswer": "Most businesses should expect to wait three to six months for a clear trend. Some technical fixes are noticed sooner, but competitive growth takes time because search engines have to recrawl the site and reassess it against other results.",
  "faqTwoQuestion": "Can you guarantee a first-page ranking?",
  "faqTwoAnswer": "No. Nobody controls Google's results, and a guaranteed page-one promise is a warning sign. We can improve the site, make better decisions and measure the outcome, but we cannot honestly promise a specific position.",
  "faqThreeQuestion": "What happens during the first month?",
  "faqThreeAnswer": "We audit the site, choose the five issues most worth addressing and either fix them or prepare them for your team. Before the month ends, we agree on the content or authority work for the next 90 days.",
  "faqFourQuestion": "Will we need to create new content?",
  "faqFourAnswer": "Possibly, but not automatically. We first look for pages that can be improved or combined. New content is recommended only when it answers a real customer question and has a clear role on the site.",
  "faqFiveQuestion": "Can you work with our existing team?",
  "faqFiveAnswer": "Yes. We regularly work alongside developers, writers and marketing teams. We can provide tickets, briefs and reviews in the format your team already uses.",
  "faqSixQuestion": "How will we know what is improving?",
  "faqSixAnswer": "We record what was changed and compare it with indexation, relevant rankings, organic traffic and enquiries. Reports explain the trend in plain English and end with the next actions.",
  "systemStoryEyebrow": "ONE SEARCH / ONE DECISION",
  "systemStoryTitleOne": "A QUESTION",
  "systemStoryTitleTwo": "ENTERS SEARCH.",
  "systemStoryTitleThree": "A DECISION LEAVES WITH TRUST.",
  "systemStoryIntroOne": "People search because they need an answer, a service or a way forward. The website has a few seconds to show that it understands the problem.",
  "systemStoryIntroTwo": "The page must be accessible, relevant and convincing. If it answers the question well and makes the next step easy, a search can become a real business conversation.",
  "systemFoundationEyebrow": "THE MOMENT OF PROOF",
  "systemFoundationTitle": "ANSWER THE QUESTION BEFORE ASKING FOR THE CONVERSION.",
  "systemFoundationNote": "QUERY / ANSWER / EVIDENCE / ACTION",
  "systemClosingEyebrow": "FROM SEARCH TO ENQUIRY",
  "systemClosingTitle": "FOUND BY THE RIGHT PERSON. CHOSEN FOR THE RIGHT REASON.",
  "systemClosingCopy": "The right person finds the page, understands the offer, sees enough evidence to trust it and knows what to do next. Every part of the site should help that happen.",
  "systemClosingLabel": "TALK ABOUT YOUR WEBSITE",
  "systemClosingHref": "contact.html",
  "aboutEyebrow": "ABOUT ORBIT",
  "aboutTitleOne": "SEO SHOULD BE",
  "aboutTitleTwo": "UNDERSTANDABLE.",
  "aboutLead": "ORBIT is an independent SEO consultancy based in Warsaw. We help service businesses and in-house teams work out why a website is underperforming and what to do about it.",
  "aboutCopy": "Most projects start with a technical audit, a content problem or a team that has too many competing priorities. We turn that uncertainty into a manageable piece of work and stay involved while it is implemented.",
  "aboutPrincipleOneTitle": "START WITH THE REAL PROBLEM",
  "aboutPrincipleOneCopy": "We look at the website, search data and business priorities before recommending a tactic.",
  "aboutPrincipleTwoTitle": "MAKE THE WORK DOABLE",
  "aboutPrincipleTwoCopy": "A short list that the team can complete is more valuable than an impressive backlog that nobody owns.",
  "aboutPrincipleThreeTitle": "STAY FOR IMPLEMENTATION",
  "aboutPrincipleThreeCopy": "We answer questions, review completed work and adjust the plan when the evidence changes.",
  "aboutPrincipalEyebrow": "ENGAGEMENT MODEL",
  "aboutPrincipalTitle": "THE CONSULTANT STAYS INVOLVED.",
  "aboutPrincipalCopy": "The person who audits the site also discusses the findings, answers implementation questions and reviews the finished work. You are not handed from a sales call to a delivery queue.",
  "principalName": "",
  "principalRole": "PRINCIPAL SEO CONSULTANT",
  "principalBio": "Your project stays with the same consultant from the first review through implementation.",
  "principalImage": "",
  "principalImageAlt": "Portrait of ORBIT's principal SEO consultant",
  "collaborateEyebrow": "A DIRECT LINE",
  "collaborateTitle": "ADVERTISE & COLLABORATE",
  "collaborateText": "We are always open to new opportunities, high-impact collaborations, and tailored business partnerships. Whether you want to advertise your brand to our audience, launch a joint project, or book our professional services, we are ready to bring your ideas to life. Every business is unique, and we don't believe in one-size-fits-all solutions. Please reach out to us using the contact form below, tell us a bit about your goals, and our team will get back to you with an exclusive, custom-tailored proposal designed strictly for your budget and objectives. Let’s build something great together.",
  "contactFormEndpoint": "contact-handler.php",
  "contactFormNameLabel": "YOUR NAME",
  "contactFormEmailLabel": "WORK EMAIL",
  "contactFormCompanyLabel": "COMPANY / WEBSITE",
  "contactFormInterestLabel": "I'M INTERESTED IN",
  "contactFormInterestPlaceholder": "CHOOSE ONE",
  "contactFormInterestSeo": "SEO CONSULTING",
  "contactFormInterestAdvertising": "ADVERTISING",
  "contactFormInterestCollaboration": "COLLABORATION",
  "contactFormInterestOther": "OTHER",
  "formInterestValues": {
    "seo-consulting": "SEO consulting",
    "advertising": "Advertising",
    "collaboration": "Collaboration",
    "other": "Other"
  },
  "contactFormMessageLabel": "TELL US ABOUT YOUR GOALS",
  "contactFormSubmitLabel": "SEND YOUR REQUEST",
  "contactFormSending": "SENDING YOUR REQUEST…",
  "contactFormSuccess": "Thank you! We have successfully received your request. Our team will review your information and get back to you shortly.",
  "contactFormError": "We could not send your request. Please try again or contact us by email.",
  "contactPageBackLabel": "BACK HOME",
  "contactPageBackHref": "index.html#about",
  "contactPageMeta": "CONTACT / NEW BUSINESS",
  "contactPageTitleOne": "TELL US WHAT'S",
  "contactPageTitleTwo": "NOT WORKING.",
  "contactPageIntro": "Tell us about the business, the website and the problem you are trying to solve. You do not need to diagnose the SEO part first.",
  "contactPageScrollLabel": "START THE CONVERSATION",
  "contactPageGuideEyebrow": "WHAT TO INCLUDE",
  "contactPageGuideTitle": "THE BUSINESS. THE WEBSITE. THE PROBLEM.",
  "contactPageGuideCopy": "A few honest sentences are enough. Tell us what the company does, what has changed and what you would like the website to achieve over the next few months.",
  "contactPageContextTitle": "THE BUSINESS",
  "contactPageContextCopy": "What you sell, who needs it and which part of the offer matters most right now.",
  "contactPageFrictionTitle": "THE PROBLEM",
  "contactPageFrictionCopy": "What is underperforming, what changed recently or where the team feels stuck.",
  "contactPageDirectionTitle": "THE OUTCOME",
  "contactPageDirectionCopy": "What you would like to be different three to six months from now.",
  "contactResponseEyebrow": "WHAT HAPPENS NEXT",
  "contactResponseTitle": "A PERSON READS EVERY MESSAGE.",
  "contactResponseOneMeta": "01 / REVIEW",
  "contactResponseOneTitle": "We read your message.",
  "contactResponseOneCopy": "We look at the website and the goal you described before deciding whether the work is a good fit.",
  "contactResponseTwoMeta": "02 / CLARIFY",
  "contactResponseTwoTitle": "We fill in the gaps.",
  "contactResponseTwoCopy": "If we need more context, we will ask a few specific questions or suggest a short call.",
  "contactResponseThreeMeta": "03 / PROPOSE",
  "contactResponseThreeTitle": "We suggest a sensible next step.",
  "contactResponseThreeCopy": "You receive a recommended scope, the expected deliverables, timing and a quote. If we are not the right fit, we will say so.",
  "contactPageFormEyebrow": "YOUR BRIEF / OUR RESPONSE",
  "contactPageFormTitle": "START WITH WHAT YOU KNOW.",
  "contactPageFormIntro": "Share what you know. We will read it, look at the site and reply with the questions or next step that makes sense.",
  "navDiscoverLabel": "HOME PAGE",
  "navDiscoverHref": "#top",
  "navWorkLabel": "THE WORK",
  "navWorkHref": "#work",
  "navServicesLabel": "SERVICES",
  "navServicesHref": "#services",
  "navServicesMenuLabel": "SELECT A SERVICE",
  "navProofLabel": "EVIDENCE",
  "navProofHref": "#proof",
  "navEngagementLabel": "WAYS TO WORK",
  "navEngagementHref": "#engagement",
  "navMethodLabel": "90 DAYS",
  "navMethodHref": "#process",
  "navInsightsLabel": "INSIGHTS",
  "navInsightsHref": "#insights",
  "navFaqLabel": "FAQ",
  "navFaqHref": "#faq",
  "navAboutLabel": "ABOUT",
  "navAboutHref": "#about",
  "navContactLabel": "CONTACT",
  "navContactHref": "contact.html",
  "navStatus": "SEARCH SYSTEMS / 2026",
  "cookieConsentVersion": "1.0",
  "cookieConsentMaxAgeDays": 180,
  "cookieBannerEyebrow": "PRIVACY / YOUR CONTROL",
  "cookieBannerStatus": "COOKIE PREFERENCES",
  "cookieBannerTitle": "YOUR CHOICE. YOUR PRIVACY.",
  "cookieBannerText": "We use browser storage to remember your cookie choice. Analytics stays off unless you choose to allow it.",
  "cookieBannerPolicyLabel": "Read the Cookies Policy",
  "cookieBannerAccept": "ACCEPT ALL",
  "cookieBannerReject": "NECESSARY ONLY",
  "cookieBannerManage": "MANAGE SETTINGS",
  "cookieBannerSave": "SAVE CHOICES",
  "cookieSettingsLabel": "COOKIE SETTINGS",
  "cookiePreferencesTitle": "CHOOSE WHAT WE CAN USE.",
  "cookieNecessaryTitle": "NECESSARY",
  "cookieNecessaryText": "Used to remember your privacy choice and keep the site working.",
  "cookieAnalyticsTitle": "ANALYTICS",
  "cookieAnalyticsText": "Allows anonymous traffic measurement if analytics is enabled on the site."
}
);
/* CONFIG_END */

;(function (config) {
  "use strict";
  if (typeof config.siteLanguage === "string" && config.siteLanguage.trim()) {
    document.documentElement.lang = config.siteLanguage.trim();
  }
  var file = location.pathname.split("/").pop() || "index.html";
  var page = config.seoPages && config.seoPages[file];
  if (!page && document.body && document.body.classList.contains("not-found-page")) {
    page = config.seoPages["404.html"];
  }
  if (!page) return;
  var base = String(config.siteUrl || location.origin).replace(/\/$/, "");
  var url = base + "/" + String(page.path || "").replace(/^\//, "");
  var ensureMeta = function (selector, attrs) {
    var node = document.head.querySelector(selector);
    if (!node) {
      node = document.createElement("meta");
      document.head.appendChild(node);
    }
    Object.keys(attrs).forEach(function (key) { node.setAttribute(key, attrs[key]); });
  };
  var canonical = document.head.querySelector('link[rel="canonical"]');
  if (!canonical) {
    canonical = document.createElement("link");
    canonical.rel = "canonical";
    document.head.appendChild(canonical);
  }
  canonical.href = url;
  document.title = page.title;
  var description = document.head.querySelector('meta[name="description"]');
  if (!description) {
    description = document.createElement("meta");
    description.name = "description";
    document.head.appendChild(description);
  }
  description.content = page.description;
  ensureMeta('meta[property="og:type"]', { property: "og:type", content: page.type === "ProfessionalService" ? "website" : "article" });
  ensureMeta('meta[property="og:site_name"]', { property: "og:site_name", content: config.companyName });
  ensureMeta('meta[property="og:title"]', { property: "og:title", content: page.title });
  ensureMeta('meta[property="og:description"]', { property: "og:description", content: page.description });
  ensureMeta('meta[property="og:url"]', { property: "og:url", content: url });
  ensureMeta('meta[property="og:image"]', { property: "og:image", content: config.socialImage });
  ensureMeta('meta[property="og:image:alt"]', { property: "og:image:alt", content: "BE FOUND — ORBIT SEO Consulting" });
  ensureMeta('meta[name="twitter:card"]', { name: "twitter:card", content: "summary_large_image" });
  ensureMeta('meta[name="twitter:title"]', { name: "twitter:title", content: page.title });
  ensureMeta('meta[name="twitter:description"]', { name: "twitter:description", content: page.description });
  ensureMeta('meta[name="twitter:image"]', { name: "twitter:image", content: config.socialImage });
  if (page.noindex) ensureMeta('meta[name="robots"]', { name: "robots", content: "noindex,follow" });
  var icons = Array.prototype.slice.call(document.head.querySelectorAll('link[rel~="icon"]'));
  var icon = icons[0] || document.createElement("link");
  icon.rel = "icon";
  icon.href = config.faviconHref;
  if (!icon.parentNode) document.head.appendChild(icon);
  icons.slice(1).forEach(function (item) { item.remove(); });
  var schema = {
    "@context": "https://schema.org",
    "@type": page.type,
    name: page.serviceType || page.title,
    url: url,
    description: page.description
  };
  if (page.type === "ProfessionalService") {
    schema.name = config.companyName;
    schema.email = String(config.corporateEmail || "").toLowerCase();
    schema.address = config.companyAddress;
    schema.areaServed = "International";
    schema.serviceType = ["SEO consulting", "Technical SEO", "SEO content strategy", "SEO authority consulting"];
  } else if (page.type === "Service") {
    schema.provider = { "@type": "ProfessionalService", name: config.companyName, url: base + "/" };
    schema.serviceType = page.serviceType;
  } else {
    schema.isPartOf = { "@type": "WebSite", name: config.companyName, url: base + "/" };
  }
  var schemaNode = document.head.querySelector('script[data-site-schema]') || document.createElement("script");
  schemaNode.type = "application/ld+json";
  schemaNode.dataset.siteSchema = "";
  schemaNode.textContent = JSON.stringify(schema);
  if (!schemaNode.parentNode) document.head.appendChild(schemaNode);
})(window.SITE_CONFIG);
