/* CONFIG_START: keep the object below valid JSON so contact-handler.php can read it. */
window.SITE_CONFIG = Object.freeze(
{
  "siteUrl": "https://orbit-seo.com",
  "siteLanguage": "en",
  "socialImage": "https://orbit-seo.com/assets/images/orbit-social-preview-v1.png",
  "faviconHref": "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23050504'/%3E%3Ctext x='7' y='29' fill='%23f0ede4' font-family='Arial' font-weight='900' font-size='25'%3EOR%3C/text%3E%3Ctext x='7' y='53' fill='%23f0ede4' font-family='Arial' font-weight='900' font-size='25'%3EBIT%3C/text%3E%3Crect x='49' y='55' width='9' height='3' fill='%23d8ff00'/%3E%3C/svg%3E",
  "seoPages": {
    "index.html": {"path": "", "title": "BE FOUND — ORBIT SEO Consulting", "description": "Independent SEO consulting that makes websites easier to discover, understand and trust through technical clarity, useful content and credible authority.", "type": "ProfessionalService"},
    "audit-technical-seo.html": {"path": "audit-technical-seo.html", "title": "Audit & Technical SEO — ORBIT SEO Consulting", "description": "A practical technical SEO audit that finds crawl, indexation, page signal and internal architecture problems, then turns them into an ordered implementation plan.", "type": "Service", "serviceType": "SEO Audit and Technical SEO"},
    "content-strategy.html": {"path": "content-strategy.html", "title": "Content Strategy — ORBIT SEO Consulting", "description": "SEO content strategy built from search intent, business value and clear information architecture — from opportunity mapping to briefs and optimization.", "type": "Service", "serviceType": "SEO Content Strategy"},
    "authority-growth.html": {"path": "authority-growth.html", "title": "Authority & Growth — ORBIT SEO Consulting", "description": "Authority and sustainable SEO growth through credible references, connected expertise, link-earning assets and disciplined performance reviews.", "type": "Service", "serviceType": "SEO Authority and Growth Consulting"},
    "contact.html": {"path": "contact.html", "title": "Contact — ORBIT SEO Consulting", "description": "Contact ORBIT SEO Consulting about SEO services, advertising opportunities and tailored business collaborations.", "type": "ContactPage"},
    "privacy-policy.html": {"path": "privacy-policy.html", "title": "Privacy Policy — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Privacy Policy explaining how personal data is collected, used, shared, retained and protected.", "type": "WebPage"},
    "cookies-policy.html": {"path": "cookies-policy.html", "title": "Cookies Policy — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Cookies Policy explaining consent choices, the current storage inventory and available browser controls.", "type": "WebPage"},
    "terms-of-service.html": {"path": "terms-of-service.html", "title": "Terms of Service — ORBIT SEO Consulting", "description": "ORBIT SEO Consulting Terms of Service governing use of the website, enquiries, website content and the relationship to separate consulting agreements.", "type": "WebPage"},
    "404.html": {"path": "404.html", "title": "Page Not Found — ORBIT SEO Consulting", "description": "The requested page could not be found. Return to ORBIT SEO Consulting or explore our SEO services.", "type": "WebPage", "noindex": true}
  },
  "brandName": "ORBIT",
  "brandDescriptor": "SEO CONSULTING",
  "heroEyebrow": "SEARCH AS A LIVING SYSTEM",
  "heroCopy": "We shape how machines discover,\nunderstand and remember\nyour brand.",
  "heroStatement": "DISCOVERED / UNDERSTOOD / TRUSTED",
  "sceneTwoKicker": "DISCOVERY IS ONLY THE FIRST SIGNAL",
  "sceneTwoWordOne": "WHAT IS FOUND",
  "sceneTwoWordTwo": "MUST BE UNDERSTOOD.",
  "sceneTwoCopy": "Search engines do not simply find information. They interpret relationships, context and intent.",
  "sceneThreeTitle": "ORBIT",
  "sceneThreeCopy": "Visibility attracts attention. Authority creates orbit.",
  "workKicker": "SEO IS PRACTICAL WORK",
  "workTitleOne": "VISIBILITY",
  "workTitleTwo": "IS BUILT.",
  "workIntroCopy": "Four disciplines enter. One coherent search presence leaves.",
  "workAuditTitle": "AUDIT",
  "workAuditCopy": "See the whole system.",
  "workTechnicalTitle": "TECHNICAL",
  "workTechnicalCopy": "Remove the friction.",
  "workContentTitle": "CONTENT",
  "workContentCopy": "Shape the meaning.",
  "workAuthorityTitle": "AUTHORITY",
  "workAuthorityCopy": "Earn the gravity.",
  "workVerdictOne": "RANKINGS ARE NOT PROMISED.",
  "workVerdictTwo": "THE CONDITIONS FOR THEM ARE BUILT.",
  "servicesEyebrow": "THE PRACTICE",
  "servicesTitle": "WHAT WE ACTUALLY DO.",
  "servicesIntro": "We make websites easier for search engines to crawl, understand and trust — then build a focused plan for what comes next.",
  "auditEyebrow": "AUDIT & TECHNICAL SEO",
  "auditSectionTitle": "Find what is blocking visibility.",
  "auditSectionCopy": "We inspect how the site is discovered, crawled and interpreted. The result is not a hundred-page document of equal-weight problems, but an ordered plan built around impact.",
  "auditItemOneTitle": "SEO audit and priority map",
  "auditItemOneCopy": "We examine crawlability, index coverage, templates and site structure, then turn the findings into a ranked backlog based on business impact, urgency and implementation effort.",
  "auditItemTwoTitle": "Titles, headings and page structure",
  "auditItemTwoCopy": "We clarify the purpose of priority pages through titles, heading hierarchy and page structure, while preserving the brand voice and avoiding mechanical keyword repetition.",
  "auditItemThreeTitle": "Internal linking and crawl paths",
  "auditItemThreeCopy": "We find isolated pages, weak pathways and wasted authority, then create useful routes from established content toward the pages that matter most.",
  "auditItemFourTitle": "Indexation and technical foundations",
  "auditItemFourCopy": "Canonicals, robots directives, sitemaps, redirects, duplicate URLs and response codes are reviewed as one system, with implementation notes your development team can act on.",
  "contentEyebrow": "CONTENT STRATEGY",
  "contentSectionTitle": "Turn search demand into useful pages.",
  "contentSectionCopy": "We map the language your audience uses, connect it to real business priorities and create an editorial system in which every page has a reason to exist.",
  "contentItemOneTitle": "Keyword and search-intent mapping",
  "contentItemOneCopy": "Queries are grouped by the problem behind them, the stage of the decision and the page best suited to answer. This reveals gaps and prevents multiple pages from competing for the same intent.",
  "contentItemTwoTitle": "Content architecture",
  "contentItemTwoCopy": "We organize commercial and educational pages into a clear hierarchy so people and search engines can understand how individual subjects contribute to the larger area of expertise.",
  "contentItemThreeTitle": "Editorial briefs and page planning",
  "contentItemThreeCopy": "Each brief defines the search purpose, essential questions, supporting evidence, internal links and next action, giving writers direction without dictating lifeless copy.",
  "contentItemFourTitle": "On-page optimization",
  "contentItemFourCopy": "We improve the signals already present across copy, metadata, headings, media and internal links, prioritizing clarity and usefulness over keyword density.",
  "authorityEyebrow": "AUTHORITY & GROWTH",
  "authoritySectionTitle": "Build reasons to be trusted.",
  "authoritySectionCopy": "Authority grows when useful information earns credible recognition over time. We build that direction deliberately and measure whether trust is actually accumulating.",
  "authorityItemOneTitle": "Link-building direction",
  "authorityItemOneCopy": "We identify the topics, assets and relationships capable of earning relevant references. The emphasis is credibility and context, not purchasing the largest possible volume of links.",
  "authorityItemTwoTitle": "Topical authority planning",
  "authorityItemTwoCopy": "Core commercial subjects are supported by connected expert content, helping the site demonstrate depth instead of producing disconnected articles around isolated keywords.",
  "authorityItemThreeTitle": "Performance reviews",
  "authorityItemThreeCopy": "Reviews connect completed work to indexation, qualified visibility, relevant traffic and conversions, separating meaningful movement from short-term ranking noise.",
  "authorityItemFourTitle": "Clear next-step recommendations",
  "authorityItemFourCopy": "Every review closes with an ordered set of actions, a clear owner and the signal each action is intended to change, so the strategy never dissolves into reactive tasks.",
  "serviceDetailLinkLabel": "EXPLORE THE FULL SERVICE",
  "auditPageHref": "audit-technical-seo.html",
  "contentPageHref": "content-strategy.html",
  "authorityPageHref": "authority-growth.html",
  "servicePageBackLabel": "BACK TO SERVICES",
  "servicePageBackHref": "index.html#services",
  "companyName": "ORBIT SEO CONSULTING",
  "companyAddress": "WARSAW, POLAND",
  "corporateEmail": "HELLO@ORBIT-SEO.COM",
  "corporateEmailHref": "mailto:hello@orbit-seo.com",
  "senderEmail": "no-reply@orbit-seo.com",
  "footerLegal": "© 2026 ORBIT SEO CONSULTING",
  "footerEyebrow": "ORBIT / SEO CONSULTING",
  "footerTitleOne": "BE FOUND.",
  "footerTitleTwo": "STAY UNDERSTOOD.",
  "footerCtaLabel": "START A CONVERSATION",
  "footerCtaHref": "contact.html",
  "footerExploreLabel": "EXPLORE",
  "footerServicesLabel": "SERVICES",
  "footerContactLabel": "CONTACT",
  "footerAuditLabel": "AUDIT & TECHNICAL SEO",
  "footerContentLabel": "CONTENT STRATEGY",
  "footerAuthorityLabel": "AUTHORITY & GROWTH",
  "footerPrinciple": "NO GUARANTEED RANKINGS / ONLY ACCOUNTABLE WORK",
  "footerBackToTop": "BACK TO THE TOP",
  "privacyPolicyLabel": "PRIVACY POLICY",
  "privacyPolicyHref": "privacy-policy.html",
  "cookiesPolicyLabel": "COOKIES POLICY",
  "cookiesPolicyHref": "cookies-policy.html",
  "termsOfServiceLabel": "TERMS OF SERVICE",
  "termsOfServiceHref": "terms-of-service.html",
  "legalEffectiveLabel": "EFFECTIVE DATE",
  "legalEffectiveDate": "3 AUGUST 2026",
  "legalBackLabel": "BACK HOME",
  "legalBackHref": "index.html#site-footer",
  "serviceCtaEyebrow": "UNSURE WHERE TO BEGIN?",
  "serviceCtaTitleOne": "BRING US",
  "serviceCtaTitleTwo": "THE PROBLEM.",
  "serviceCtaCopy": "You do not need an SEO diagnosis. Tell us what is changing, underperforming or unclear.",
  "serviceCtaLabel": "FIND THE RIGHT START",
  "serviceCtaHref": "contact.html",
  "evidenceEyebrow": "THE EVIDENCE STANDARD",
  "evidenceTitle": "PROOF BEFORE PROMISES.",
  "evidenceIntro": "We do not manufacture dramatic graphs or publish invented ranking wins. Progress is documented through decisions, completed changes and the business signals those changes are intended to improve.",
  "evidenceImage": "assets/images/evidence-audit-workflow-warm-v1.webp",
  "evidenceImageAlt": "SEO audit materials arranged beside a website on a laptop",
  "evidenceImageLabel": "THE WORK / MADE VISIBLE",
  "evidenceImageCaption": "An audit becomes useful when every finding carries consequence, effort and an owner.",
  "evidenceArtifactLabel": "ARTIFACT",
  "evidenceSignalLabel": "SIGNAL",
  "evidenceOneIndex": "ARTIFACT / PRIORITY MAP",
  "evidenceOneTiming": "IMPLEMENTATION READY",
  "evidenceOneTitle": "The work arrives already ordered.",
  "evidenceOneCopy": "Findings are connected to affected templates, likely consequence, implementation effort and a clear owner. Your team receives a decision tool, not an undifferentiated export.",
  "evidenceOneArtifact": "Issue map / implementation notes",
  "evidenceOneSignal": "Crawl, indexation and template clarity",
  "evidenceTwoIndex": "ARTIFACT / DECISION RECORD",
  "evidenceTwoTiming": "RATIONALE INCLUDED",
  "evidenceTwoTitle": "Every page decision keeps its reason.",
  "evidenceTwoCopy": "Recommendations preserve the evidence behind them: the audience need, business value, affected page and intended signal. Context survives handoff instead of disappearing into a task list.",
  "evidenceTwoArtifact": "Decision log / page rationale",
  "evidenceTwoSignal": "Purpose, ownership and implementation clarity",
  "evidenceThreeIndex": "ARTIFACT / MEASUREMENT REVIEW",
  "evidenceThreeTiming": "BUSINESS CONTEXT",
  "evidenceThreeTitle": "Movement is explained, not decorated.",
  "evidenceThreeCopy": "Reviews separate shipped work, search response and business outcome. What changed, what did not and what deserves attention next remain visible without manufacturing certainty.",
  "evidenceThreeArtifact": "Change record / review narrative",
  "evidenceThreeSignal": "Qualified visibility, journeys and conversions",
  "evidenceNote": "CLIENT-SPECIFIC CASE STUDIES ARE PUBLISHED ONLY WITH PERMISSION. NO FICTIONAL METRICS.",
  "evidenceCta": "ASK FOR RELEVANT EXPERIENCE",
  "fitEyebrow": "WORKING FIT",
  "fitTitle": "RIGHT PROBLEM. RIGHT PARTNERSHIP.",
  "fitIntro": "The work moves fastest when the business has genuine expertise, a site worth improving and people able to turn clear recommendations into real changes.",
  "fitPositiveLabel": "A STRONG FIT",
  "fitPositiveOneTitle": "Established service and B2B businesses",
  "fitPositiveOneCopy": "You have a meaningful offer, but search does not yet communicate its full value.",
  "fitPositiveTwoTitle": "Teams ready to implement",
  "fitPositiveTwoCopy": "A developer, writer or decision-maker can act on an ordered plan.",
  "fitPositiveThreeTitle": "Experts with something useful to say",
  "fitPositiveThreeCopy": "The business can contribute real experience, evidence and perspective.",
  "fitNegativeLabel": "NOT THE RIGHT FIT",
  "fitNegativeOneTitle": "Guaranteed rankings",
  "fitNegativeOneCopy": "No responsible consultant controls Google or promises page one in 30 days.",
  "fitNegativeTwoTitle": "Bulk content for its own sake",
  "fitNegativeTwoCopy": "Publishing volume is not a strategy when pages have no distinct purpose.",
  "fitNegativeThreeTitle": "Paid-link shortcuts",
  "fitNegativeThreeCopy": "We will not trade durable trust for a temporary and avoidable risk.",
  "engagementEyebrow": "WAYS TO WORK TOGETHER",
  "engagementTitle": "A SCOPE YOU CAN SEE.",
  "engagementIntro": "Every engagement begins with a written scope, defined outputs and a clear decision point. Pricing is tailored only after we understand the site, team and implementation reality.",
  "collaborationImage": "assets/images/client-collaboration-warm-v1.webp",
  "collaborationImageAlt": "SEO consultant and client team reviewing website pages together",
  "collaborationImageLabel": "SHARED CONTEXT / CLEAR OWNERSHIP",
  "collaborationImageCaption": "One working session. Shared context. A scope shaped around the team that must implement it.",
  "engagementOneMeta": "DIAGNOSTIC / 2–4 WEEKS",
  "engagementOneTitle": "SEO Diagnostic Sprint",
  "engagementOneCopy": "A focused audit, the five highest-impact priorities and an implementation-ready direction for the next 90 days.",
  "engagementOnePrice": "FIXED SCOPE / CUSTOM QUOTE",
  "engagementTwoMeta": "PROGRAM / 90 DAYS",
  "engagementTwoTitle": "Search Growth Direction",
  "engagementTwoCopy": "Technical correction, content architecture and authority priorities coordinated as one measurable program.",
  "engagementTwoPrice": "PROJECT SCOPE / CUSTOM QUOTE",
  "engagementThreeMeta": "ADVISORY / MONTHLY",
  "engagementThreeTitle": "Ongoing SEO Advisory",
  "engagementThreeCopy": "Senior guidance for internal teams that need prioritization, implementation review and a reliable decision partner.",
  "engagementThreePrice": "MONTHLY SCOPE / CUSTOM QUOTE",
  "engagementCta": "DISCUSS THE RIGHT SCOPE",
  "methodEyebrow": "A CLEAR START",
  "methodTitle": "THE FIRST 90 DAYS.",
  "methodIntro": "Every engagement begins with a defined sequence. You know what is being reviewed, what is being changed and what we will measure next.",
  "methodImage": "assets/images/seo-90-day-plan-warm-v1.webp",
  "methodImageAlt": "A practical SEO audit, five priority cards and a 90-day roadmap on a worktable",
  "methodImageLabel": "AUDIT / PRIORITIZE / BUILD",
  "methodImageCaption": "Audit, five priorities, then a 90-day direction. The sequence stays visible from the first decision onward.",
  "methodAuditTitle": "Audit the system.",
  "methodAuditCopy": "Map the site, its search signals and the issues limiting discovery.",
  "methodFixTitle": "Fix what matters first.",
  "methodFixCopy": "Resolve the five highest-impact problems instead of reacting to noise.",
  "methodPlanTitle": "Build the next layer.",
  "methodPlanCopy": "Execute the agreed content or authority plan and establish measurable reporting.",
  "expectationKicker": "AN HONEST EXPECTATION",
  "expectationTitle": "SEO moves in months, not moments.",
  "expectationCopy": "Meaningful changes usually become visible in three to six months while search engines crawl, reassess and compare. Anyone guaranteeing page one in 30 days is overselling.",
  "insightsEyebrow": "FIELD NOTES",
  "insightsTitle": "THE FUNDAMENTALS TRAVEL FURTHER.",
  "insightsIntro": "Three practical notes for teams that want to make better search decisions before chasing another tactic.",
  "insightOneMeta": "TECHNICAL / 06 MIN",
  "insightOneTitle": "What an SEO audit should help you decide",
  "insightOneCopyOne": "An audit is useful only when it changes the order of work. A long export of warnings gives every issue equal visual weight, even though very few issues deserve equal business priority.",
  "insightOneCopyTwo": "A decision-ready audit explains the affected templates, the search consequence, the implementation effort and who needs to act. It should make the next five moves obvious.",
  "insightTwoMeta": "CONTENT / 07 MIN",
  "insightTwoTitle": "Why more content is often the wrong first move",
  "insightTwoCopyOne": "A site can publish every week and still remain difficult to understand. New pages create value only when they answer a distinct need, strengthen an area of expertise and connect naturally to a useful next action.",
  "insightTwoCopyTwo": "Before commissioning another article, clarify which intent it owns, what existing page it supports and what evidence only your business can contribute.",
  "insightThreeMeta": "AUTHORITY / 05 MIN",
  "insightThreeTitle": "A credible link has context before it has a metric",
  "insightThreeCopyOne": "Authority is not improved by collecting the largest possible number of references. A useful link appears where the audience, subject and reason for citation genuinely overlap.",
  "insightThreeCopyTwo": "The strongest direction starts with assets and expertise worth referencing, then identifies the publications, communities and relationships where that evidence belongs.",
  "insightServiceLink": "EXPLORE THE RELATED SERVICE",
  "faqEyebrow": "BEFORE WE BEGIN",
  "faqTitle": "FAQ.",
  "faqIntro": "Clear expectations make better work. Here are the questions worth answering before an SEO engagement begins.",
  "faqFootnote": "ASK BETTER / BUILD BETTER",
  "faqOneQuestion": "How long does SEO take to show results?",
  "faqOneAnswer": "Meaningful movement usually takes three to six months. Search engines need time to crawl changes, reassess the site and compare its authority with competing results.",
  "faqTwoQuestion": "Can you guarantee a first-page ranking?",
  "faqTwoAnswer": "No responsible consultant can guarantee a specific ranking or a 30-day jump to page one. We build the technical, editorial and authority conditions that make sustainable growth possible.",
  "faqThreeQuestion": "What happens during the first month?",
  "faqThreeAnswer": "We audit the site, identify the five issues causing the greatest loss of visibility, fix or scope those priorities and agree on a focused 90-day content or authority plan.",
  "faqFourQuestion": "Will we need to create new content?",
  "faqFourAnswer": "Only where search demand and business value justify it. We first improve what already exists, then map genuine content gaps instead of publishing for volume alone.",
  "faqFiveQuestion": "Can you work with our existing team?",
  "faqFiveAnswer": "Yes. We can collaborate with your developers, writers and marketing team, providing clear priorities, implementation guidance and review rather than creating another disconnected workflow.",
  "faqSixQuestion": "How will we know what is improving?",
  "faqSixAnswer": "We connect completed work to measurable signals such as indexation, qualified visibility, relevant traffic and business-focused conversions, then make the next priorities explicit.",
  "systemStoryEyebrow": "ONE SEARCH / ONE DECISION",
  "systemStoryTitleOne": "A QUESTION",
  "systemStoryTitleTwo": "ENTERS SEARCH.",
  "systemStoryTitleThree": "A DECISION LEAVES WITH TRUST.",
  "systemStoryIntroOne": "Someone arrives with a problem, not a keyword list. The site has seconds to show that it recognizes the situation and has a credible answer.",
  "systemStoryIntroTwo": "Technical access gets the page considered. Clear language makes it relevant. Evidence and a useful next step turn discovery into a business conversation.",
  "systemFoundationEyebrow": "THE MOMENT OF PROOF",
  "systemFoundationTitle": "ANSWER THE QUESTION BEFORE ASKING FOR THE CONVERSION.",
  "systemFoundationNote": "QUERY / ANSWER / EVIDENCE / ACTION",
  "systemClosingEyebrow": "THE COMPLETE JOURNEY",
  "systemClosingTitle": "FOUND BY THE RIGHT PERSON. CHOSEN FOR THE RIGHT REASON.",
  "systemClosingCopy": "A useful search journey moves from recognition to understanding, from understanding to confidence, and from confidence to an action the business can measure.",
  "systemClosingLabel": "MAP YOUR SEARCH JOURNEY",
  "systemClosingHref": "contact.html",
  "aboutEyebrow": "ABOUT ORBIT",
  "aboutTitleOne": "SEO SHOULD BE",
  "aboutTitleTwo": "UNDERSTANDABLE.",
  "aboutLead": "ORBIT is an independent SEO consultancy for businesses that want a clearer, more durable way to grow through search.",
  "aboutCopy": "We work at the point where technical structure, useful content and earned authority meet. Every recommendation has a reason, an owner and a measurable signal behind it.",
  "aboutPrincipleOneTitle": "PRACTICAL BEFORE THEATRICAL",
  "aboutPrincipleOneCopy": "We identify what is limiting visibility, order the work by impact and make the next decision explicit.",
  "aboutPrincipleTwoTitle": "CLARITY OVER VOLUME",
  "aboutPrincipleTwoCopy": "Fewer priorities, better explained and properly implemented, outperform a backlog no one can act on.",
  "aboutPrincipleThreeTitle": "BUILT TO COMPOUND",
  "aboutPrincipleThreeCopy": "The goal is not a temporary ranking spike. It is a site that becomes easier to discover, understand and trust over time.",
  "aboutPrincipalEyebrow": "ENGAGEMENT MODEL",
  "aboutPrincipalTitle": "SENIOR ATTENTION. NO DELIVERY THEATRE.",
  "aboutPrincipalCopy": "The person responsible for the diagnosis stays close to implementation and review. Context is not lost between a sales call, a strategy deck and the people doing the work.",
  "principalName": "",
  "principalRole": "PRINCIPAL SEO CONSULTANT",
  "principalBio": "Add the principal consultant's verified experience, specialist background and working philosophy here.",
  "principalImage": "",
  "principalImageAlt": "Portrait of ORBIT's principal SEO consultant",
  "collaborateEyebrow": "A DIRECT LINE",
  "collaborateTitle": "ADVERTISE & COLLABORATE",
  "collaborateText": "We are always open to new opportunities, high-impact collaborations, and tailored business partnerships. Whether you want to advertise your brand to our audience, launch a joint project, or book our professional services, we are ready to bring your ideas to life. Every business is unique, and we don't believe in one-size-fits-all solutions. Please reach out to us using the contact form below, tell us a bit about your goals, and our team will get back to you with an exclusive, custom-tailored proposal designed strictly for your budget and objectives. Let’s build something great together.",
  "contactFormEndpoint": "contact-handler.php",
  "contactFormNameLabel": "YOUR NAME",
  "contactFormEmailLabel": "WORK EMAIL",
  "contactFormCompanyLabel": "COMPANY / WEBSITE",
  "contactFormInterestLabel": "I'M INTERESTED IN",
  "contactFormInterestPlaceholder": "SELECT A DIRECTION",
  "contactFormInterestSeo": "SEO CONSULTING",
  "contactFormInterestAdvertising": "ADVERTISING",
  "contactFormInterestCollaboration": "COLLABORATION",
  "contactFormInterestOther": "OTHER",
  "formInterestValues": {
    "seo-consulting": "SEO consulting",
    "advertising": "Advertising",
    "collaboration": "Collaboration",
    "other": "Other"
  },
  "contactFormMessageLabel": "TELL US ABOUT YOUR GOALS",
  "contactFormSubmitLabel": "SEND YOUR REQUEST",
  "contactFormSending": "SENDING YOUR REQUEST…",
  "contactFormSuccess": "Thank you! We have successfully received your request. Our team will review your information and get back to you shortly.",
  "contactFormError": "We could not send your request. Please try again or contact us by email.",
  "contactPageBackLabel": "BACK HOME",
  "contactPageBackHref": "index.html#about",
  "contactPageMeta": "CONTACT / NEW BUSINESS",
  "contactPageTitleOne": "MAKE THE NEXT",
  "contactPageTitleTwo": "MOVE CLEAR.",
  "contactPageIntro": "Tell us where the business is going, what the website is expected to do and what currently feels unclear. We will start with the useful questions.",
  "contactPageScrollLabel": "START THE CONVERSATION",
  "contactPageGuideEyebrow": "A USEFUL FIRST MESSAGE",
  "contactPageGuideTitle": "GIVE US THE CONTEXT. WE'LL FIND THE SEARCH OPPORTUNITY.",
  "contactPageGuideCopy": "You do not need to arrive with an SEO diagnosis. A concise picture of the business, the website and the outcome you need is enough for us to prepare a focused response.",
  "contactPageContextTitle": "THE BUSINESS",
  "contactPageContextCopy": "What you sell, who needs it and which part of the offer matters most right now.",
  "contactPageFrictionTitle": "THE FRICTION",
  "contactPageFrictionCopy": "What is underperforming, changing or becoming difficult for the team to explain.",
  "contactPageDirectionTitle": "THE DIRECTION",
  "contactPageDirectionCopy": "What a useful outcome would look like over the next three to six months.",
  "contactResponseEyebrow": "WHAT HAPPENS NEXT",
  "contactResponseTitle": "NO GENERIC SALES SEQUENCE.",
  "contactResponseOneMeta": "01 / REVIEW",
  "contactResponseOneTitle": "We read the context.",
  "contactResponseOneCopy": "The request is reviewed against the business goal, the current site and the kind of support you are asking for.",
  "contactResponseTwoMeta": "02 / CLARIFY",
  "contactResponseTwoTitle": "We ask only useful questions.",
  "contactResponseTwoCopy": "If scope is unclear, we identify the missing information before suggesting work or arranging a conversation.",
  "contactResponseThreeMeta": "03 / PROPOSE",
  "contactResponseThreeTitle": "You receive a tailored next step.",
  "contactResponseThreeCopy": "The response explains the recommended engagement, expected outputs, timing and a custom quote.",
  "contactPageFormEyebrow": "YOUR BRIEF / OUR RESPONSE",
  "contactPageFormTitle": "START WITH WHAT YOU KNOW.",
  "contactPageFormIntro": "Share the essentials below. We will review the request and respond with the most relevant next step, not a generic sales sequence.",
  "navDiscoverLabel": "HOME PAGE",
  "navDiscoverHref": "#top",
  "navWorkLabel": "THE WORK",
  "navWorkHref": "#work",
  "navServicesLabel": "SERVICES",
  "navServicesHref": "#services",
  "navServicesMenuLabel": "SELECT A SERVICE",
  "navProofLabel": "EVIDENCE",
  "navProofHref": "#proof",
  "navEngagementLabel": "WAYS TO WORK",
  "navEngagementHref": "#engagement",
  "navMethodLabel": "90 DAYS",
  "navMethodHref": "#process",
  "navInsightsLabel": "INSIGHTS",
  "navInsightsHref": "#insights",
  "navFaqLabel": "FAQ",
  "navFaqHref": "#faq",
  "navAboutLabel": "ABOUT",
  "navAboutHref": "#about",
  "navContactLabel": "CONTACT",
  "navContactHref": "contact.html",
  "navStatus": "SEARCH SYSTEMS / 2026",
  "cookieConsentVersion": "1.0",
  "cookieConsentMaxAgeDays": 180,
  "cookieBannerEyebrow": "PRIVACY / YOUR CONTROL",
  "cookieBannerStatus": "CONSENT SIGNAL",
  "cookieBannerTitle": "YOUR CHOICE. YOUR SIGNAL.",
  "cookieBannerText": "We use necessary browser storage to remember your choices. Optional analytics can be activated only when you allow them.",
  "cookieBannerPolicyLabel": "Read the Cookies Policy",
  "cookieBannerAccept": "ACCEPT ALL",
  "cookieBannerReject": "NECESSARY ONLY",
  "cookieBannerManage": "MANAGE SETTINGS",
  "cookieBannerSave": "SAVE CHOICES",
  "cookieSettingsLabel": "COOKIE SETTINGS",
  "cookiePreferencesTitle": "CONTROL THE SIGNAL.",
  "cookieNecessaryTitle": "NECESSARY",
  "cookieNecessaryText": "Required to remember privacy choices and keep the site working.",
  "cookieAnalyticsTitle": "ANALYTICS",
  "cookieAnalyticsText": "Allows anonymous measurement when an analytics service is configured."
}
);
/* CONFIG_END */

;(function (config) {
  "use strict";
  if (typeof config.siteLanguage === "string" && config.siteLanguage.trim()) {
    document.documentElement.lang = config.siteLanguage.trim();
  }
  var file = location.pathname.split("/").pop() || "index.html";
  var page = config.seoPages && config.seoPages[file];
  if (!page && document.body && document.body.classList.contains("not-found-page")) {
    page = config.seoPages["404.html"];
  }
  if (!page) return;
  var base = String(config.siteUrl || location.origin).replace(/\/$/, "");
  var url = base + "/" + String(page.path || "").replace(/^\//, "");
  var ensureMeta = function (selector, attrs) {
    var node = document.head.querySelector(selector);
    if (!node) {
      node = document.createElement("meta");
      document.head.appendChild(node);
    }
    Object.keys(attrs).forEach(function (key) { node.setAttribute(key, attrs[key]); });
  };
  var canonical = document.head.querySelector('link[rel="canonical"]');
  if (!canonical) {
    canonical = document.createElement("link");
    canonical.rel = "canonical";
    document.head.appendChild(canonical);
  }
  canonical.href = url;
  document.title = page.title;
  var description = document.head.querySelector('meta[name="description"]');
  if (!description) {
    description = document.createElement("meta");
    description.name = "description";
    document.head.appendChild(description);
  }
  description.content = page.description;
  ensureMeta('meta[property="og:type"]', { property: "og:type", content: page.type === "ProfessionalService" ? "website" : "article" });
  ensureMeta('meta[property="og:site_name"]', { property: "og:site_name", content: config.companyName });
  ensureMeta('meta[property="og:title"]', { property: "og:title", content: page.title });
  ensureMeta('meta[property="og:description"]', { property: "og:description", content: page.description });
  ensureMeta('meta[property="og:url"]', { property: "og:url", content: url });
  ensureMeta('meta[property="og:image"]', { property: "og:image", content: config.socialImage });
  ensureMeta('meta[property="og:image:alt"]', { property: "og:image:alt", content: "BE FOUND — ORBIT SEO Consulting" });
  ensureMeta('meta[name="twitter:card"]', { name: "twitter:card", content: "summary_large_image" });
  ensureMeta('meta[name="twitter:title"]', { name: "twitter:title", content: page.title });
  ensureMeta('meta[name="twitter:description"]', { name: "twitter:description", content: page.description });
  ensureMeta('meta[name="twitter:image"]', { name: "twitter:image", content: config.socialImage });
  if (page.noindex) ensureMeta('meta[name="robots"]', { name: "robots", content: "noindex,follow" });
  var icons = Array.prototype.slice.call(document.head.querySelectorAll('link[rel~="icon"]'));
  var icon = icons[0] || document.createElement("link");
  icon.rel = "icon";
  icon.href = config.faviconHref;
  if (!icon.parentNode) document.head.appendChild(icon);
  icons.slice(1).forEach(function (item) { item.remove(); });
  var schema = {
    "@context": "https://schema.org",
    "@type": page.type,
    name: page.serviceType || page.title,
    url: url,
    description: page.description
  };
  if (page.type === "ProfessionalService") {
    schema.name = config.companyName;
    schema.email = String(config.corporateEmail || "").toLowerCase();
    schema.address = config.companyAddress;
    schema.areaServed = "International";
    schema.serviceType = ["SEO consulting", "Technical SEO", "SEO content strategy", "SEO authority consulting"];
  } else if (page.type === "Service") {
    schema.provider = { "@type": "ProfessionalService", name: config.companyName, url: base + "/" };
    schema.serviceType = page.serviceType;
  } else {
    schema.isPartOf = { "@type": "WebSite", name: config.companyName, url: base + "/" };
  }
  var schemaNode = document.head.querySelector('script[data-site-schema]') || document.createElement("script");
  schemaNode.type = "application/ld+json";
  schemaNode.dataset.siteSchema = "";
  schemaNode.textContent = JSON.stringify(schema);
  if (!schemaNode.parentNode) document.head.appendChild(schemaNode);
})(window.SITE_CONFIG);
